name: Docker Image CI (build only)

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [focal-python, bionic-python, xenial-python]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd ${{ matrix.image }} && docker build . --file Dockerfile --tag ${{ matrix.image }}:$(date +%Y%m%d)
